# f1 = open("abc.txt","r")
# data = f1.read()
# f1.close()
# f2 = open("pqr.txt","w")
# f2.write(data)
# f2.close()

# ss = input("which file you want to copy ?")
# f1 = open(ss,"r")
# data = f1.read()
# f1.close()
# f2 = open(ss.replace(".txt","_copy.txt"), "w")
# f2.write(data)
# f2.close()

file = input("which file you want to process ?")
count_word = input("which word you want to count ?")
f1 = open(file,"r")
data = f1.read()
count = data.count(count_word)
f1.close()
print(f"the word {count_word} is present {count} times in the file {file}")
